version: '3'

services:  
  rnamaps-nginx:
    build: .
    container_name: 'rnamaps-front-app'
    restart: always
    volumes:
      - node_modules:/node_modules
    ports:
      - "67:80"

volumes:
  node_modules:
